# version: "3.9"
services:
  backend:
    build:
      context: ./chatbot_backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/sample
    networks:
      - app_network

  frontend:
    build:
      context: ./chatbot_frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
